menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/bennyyip
  RSS: /atom.xml

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-77734675-1
